
name: "macos kind CI workflow"

on:
  push:
    branches: [ test ]
  schedule:
      # https://crontab.guru/
      # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
      # - cron:  '0 0 * * FRI' ##execution of a task in the first minute of the month  



jobs:

# https://github.com/actions/virtual-environments
  macos-latest-kind-homebrew:
      name: "On macOS via Homebrew - macos-latest"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update     
      - name: "check on brew version"
        run: brew --version         
      - name: "Get OS X System Version"
        run: sw_vers       
      - name: "Get Mac System Details with system_profiler"
        run: system_profiler | more  
      - name: "osfingerprinting"
        run: uname -a     
      # https://kind.sigs.k8s.io/docs/user/quick-start/                              
      - name: "Installing From Release Binaries"
        run: |
         curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-darwin-amd64
          chmod +x ./kind
          mv ./kind /usr/local/bin/kind

# # https://github.com/actions/virtual-environments
#   macos-11-kind-homebrew:
#       name: "On macOS via Homebrew - macos-11"
#       runs-on: macos-11
#       steps:
#       - name: Checkout
#         uses: actions/checkout@v1
#       - name: "brew update"
#         run: brew update     
#       - name: "check on brew version"
#         run: brew --version         
#       - name: "Get OS X System Version"
#         run: sw_vers       
#       - name: "Get Mac System Details with system_profiler"
#         run: system_profiler | more  
#       - name: "osfingerprinting"
#         run: uname -a     
#       # https://kind.sigs.k8s.io/docs/user/quick-start/                              
#       - name: "On macOS via Homebrew"
#         run: brew install kind 

# # https://github.com/actions/virtual-environments
#   macos-10.15-kind-homebrew:
#       name: "On macOS via Homebrew - macos-10.15"
#       runs-on: macos-10.15
#       steps:
#       - name: Checkout
#         uses: actions/checkout@v1
#       - name: "brew update"
#         run: brew update     
#       - name: "check on brew version"
#         run: brew --version         
#       - name: "Get OS X System Version"
#         run: sw_vers       
#       - name: "Get Mac System Details with system_profiler"
#         run: system_profiler | more  
#       - name: "osfingerprinting"
#         run: uname -a     
#       # https://kind.sigs.k8s.io/docs/user/quick-start/                              
#       - name: "On macOS via Homebrew"
#         run: brew install kind 